Add a new web account
wustlcse237sp20/project-safestore pull request #37
Opened 2020-04-01 20:27 UTC by ryanloutos

2020-04-01 21:09 UTC, mbendy requested changes

2020-04-01 21:09 UTC, mbendy commented on src/websiteAccount/WebsiteAccount.java
> +			websiteAccountEntity = new WebsiteAccountEntity(safeStoreUser.getUserEntity(), Encryption.encrypt(nickname),
just for coding guidelines, this is an extremely long line, maybe encrypt each string in a variable first to reduce the line length a little?

2020-04-01 21:09 UTC, mbendy commented on src/websiteAccount/WebsiteAccount.java
> +
can you add getters/setters for nickname, login, password similar to how i did mine in CreditCard?

2020-04-01 21:09 UTC, mbendy commented on test/queryWithDatabaseTests/WebsiteAccountTests.java
> +			testUser.createSafeStoreAccount(databaseConnection);
don't use a method from User class, put the test user in the database directly using a dao, then be sure to delete it after your tests run. I'll push my tests so you can see how i did it

2020-04-01 21:09 UTC, mbendy commented on test/queryWithDatabaseTests/WebsiteAccountTests.java
> +			WebsiteAccountEntity testEntityPulledFromDb = websiteAccountDao.queryForId(testWebsiteAccountEntity.getId());
this test is confusing, why are you querying twice? just query once, make sure the data is there.  Shouldn't need to delete two things? only one row should have been added?

2020-04-01 22:52 UTC, ryanloutos commented on src/websiteAccount/WebsiteAccount.java
> +			websiteAccountEntity = new WebsiteAccountEntity(safeStoreUser.getUserEntity(), Encryption.encrypt(nickname),
line a bit short but still kind of long....think it should be good enough

2020-04-01 22:52 UTC, ryanloutos commented on src/websiteAccount/WebsiteAccount.java
> +
done

2020-04-01 22:53 UTC, ryanloutos commented on test/queryWithDatabaseTests/WebsiteAccountTests.java
> +			testUser.createSafeStoreAccount(databaseConnection);
fixed

2020-04-01 22:53 UTC, ryanloutos commented on test/queryWithDatabaseTests/WebsiteAccountTests.java
> +			WebsiteAccountEntity testEntityPulledFromDb = websiteAccountDao.queryForId(testWebsiteAccountEntity.getId());
you are right....fixed

2020-04-02 15:13 UTC, mbendy requested changes
Sorry, last thing, I forgot them too, but Javadocs :/

2020-04-02 16:39 UTC, mbendy approved these changes
looks good to me

2020-04-02 16:40 UTC, merged